import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { Navbar } from "../components/Navbar";
import { Header } from "../components/Header";
import { Main } from "../components/Main";
import { Footer } from "../components/Footer";

export const Section = styled.section`
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: start;
  gap: 4rem;
  background: radial-gradient(
    131.05% 131.05% at 51.87% -48.54%,
    #161e33 0%,
    #000000 100%
  );
  padding-top: 12rem;
  height: 100vh;
  width: 100%;
  @media (max-width: 640px) {
    padding-top: 8rem;
  }
`;

export default function Home() {
  const [mount, setMount] = useState(false);

  useEffect(() => {
    setMount(true);
  }, []);
  if (!mount) return null;

  return (
    <>
      <Head>
        <title>Clonaroo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section id="audio">
        <Navbar />
        <Header />
        <Main />
        <Footer />
      </Section>
    </>
  );
}
